version: '3.7'
services:
  postgres:
    container_name: postgres-gts
    image: "postgres:14"
    environment:
      POSTGRES_USER: antro
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: antro
    ports:
      - "5432:5432"